# 1. Business Understanding

Acute Kidney Injury (AKI) is a critical medical condition associated with high morbidity and mortality rates. Despite advances in medical care, early detection and risk stratification remain major challenges. Delayed diagnosis and intervention often result in poor patient outcomes, increased hospital stays, and higher healthcare costs.

Predicting mortality risk in AKI patients using data-driven models can help healthcare providers take proactive measures, improve clinical decision-making, and allocate resources efficiently. A robust predictive model can enable early identification of high-risk patients, allowing timely interventions that may reduce complications and improve survival rates.

This project aims to develop a machine learning-based model to predict mortality in AKI patients using relevant clinical parameters such as serum creatinine levels, urine output, demographics, comorbidities, and treatment interventions. The insights from this model can support physicians in making evidence-based decisions and improving patient outcomes.

## 1.1 Problem Statement

Acute Kidney Injury (AKI) contributes significantly to in-hospital mortality, yet current risk assessment methods are often reactive rather than predictive. Traditional clinical scoring systems may not capture the complex interactions between various risk factors, leading to suboptimal patient management.

This project seeks to develop a predictive model that leverages machine learning techniques to estimate the likelihood of mortality in AKI patients. By analyzing key patient data, the model aims to provide early warnings for high-risk cases, enabling timely clinical interventions. The goal is to improve survival rates, optimize hospital resource utilization, and enhance patient care through data-driven insights.

## 1.2 Objective
1. Predict in-hospital mortality in the ICU of a retrospective cohort of patients with AKI

# 2. Data Acquisition and Understanding

This data was downloaded from MIMIC-III(Medical Information Mart for Intensive Care) database. Each registry includes a set of variables that summarize the clinical trajectory of the patients during their stay in the ICU. The target variable, in-hospital mortality (IHM), is defined as a binary variable where the value ’1’ indicates the death of the patient in the ICU. The variables are:
- **age**: The age of the patient, usually measured in years.

- **gender_F**: A binary indicator (0 or 1) representing whether the patient is female (1 for female, 0 for not female).

- **gender_M**: A binary indicator representing whether the patient is male (1 for male, 0 for not male).

- **bic_max**: The maximum value of the Body Mass Index (BMI) recorded for the patient.

- **bic_mean**: The average Body Mass Index (BMI) of the patient over a certain period.

- **bic_min**: The minimum Body Mass Index (BMI) recorded for the patient.

- **bilirubin**: A substance produced from the breakdown of red blood cells; high levels can indicate liver problems.

- **bp_max**: The maximum recorded blood pressure of the patient.

- **bp_mean**: The average blood pressure recorded for the patient.

- **bp_min**: The minimum recorded blood pressure of the patient.

- **bun_max**: The maximum value of Blood Urea Nitrogen (BUN), which can indicate kidney function.

- **bun_mean**: The average Blood Urea Nitrogen (BUN) level for the patient.

- **bun_min**: The minimum Blood Urea Nitrogen (BUN) level recorded.

- **Days_in_uci**: The number of days the patient spent in an Intensive Care Unit (ICU).

- **fio2**: Fraction of inspired oxygen; it indicates the percentage of oxygen in the air that a patient is breathing.

- **gcs_max**: The maximum score on the Glasgow Coma Scale, which measures consciousness levels.

- **gcs_mean**: The average Glasgow Coma Scale score during the patient's stay.

- **gcs_min**: The minimum Glasgow Coma Scale score recorded.

- **hr_max**: The maximum heart rate recorded for the patient.

- **hr_mean**: The average heart rate during monitoring.

- **hr_min**: The minimum heart rate recorded.

- **max pao2**: The maximum partial pressure of oxygen in arterial blood, indicating how well oxygen is being transferred into the blood from the lungs.

- **mean pao2**: The average partial pressure of oxygen in arterial blood during monitoring.

- **min pao2**: The minimum partial pressure of oxygen in arterial blood recorded.

- **pot_max**: The maximum potassium level in the patient's blood, which is important for heart and muscle function.

- **pot_mean**: The average potassium level in the patient's blood during monitoring.

- **pot_min**: The minimum potassium level recorded in the patient's blood.

- **sod_max**: The maximum sodium level in the patient's blood, important for fluid balance and nerve function.

- **sod_mean**: The average sodium level during monitoring.

- **sod_min**: The minimum sodium level recorded in the patient's blood.

- **temp**: The body temperature of the patient, usually measured in degrees Celsius or Fahrenheit.

- **wbc_max**: The maximum white blood cell count, which can indicate infection or inflammation.

- **wbc_mean**: The average white blood cell count during monitoring.

- **wbc_min**: The minimum white blood cell count recorded.

- **IHM**: stands for In-Hospital Mortality, indicating whether a patient died during their hospital stay (often coded as 1 for yes and 0 for no).

# 3. Data Preparation

In [2]:
# importing libraries
import pandas as pd
#from matplotlib import pyplot as plt

In [7]:
# import data

data_path = r"C:\Users\njamb\Desktop\DataScience\AcuteKidneyInjuryMortalityPrediction\data\raw\ihm_aki.csv"
data = pd.read_csv(data_path, index_col=0)
data.head()

,age,gender_F,gender_M,bic_max,bic_mean,bic_min,bilirubin,bp_max,bp_mean,bp_min,...,pot_mean,pot_min,sod_max,sod_mean,sod_min,temp,wbc_max,wbc_mean,wbc_min,IHM
0,74.63,1,0,40.0,34.62,30.0,0.4,154.63,123.28,98.69,...,3.85,3.30,143.50,141.50,139.0,NaN,13.70,9.20,6.4,0
1,60.12,1,0,34.0,28.94,24.0,0.2,113.12,104.68,93.88,...,3.76,2.75,145.00,141.21,139.0,38.04,21.30,17.69,14.4,0
2,64.12,1,0,26.0,24.07,21.0,0.3,126.62,108.91,77.00,...,3.86,3.50,145.00,140.86,138.0,NaN,33.90,19.39,10.5,0
4,54.46,0,1,34.0,30.98,26.0,1.0,151.38,114.38,97.21,...,4.17,3.60,147.50,140.43,135.0,36.83,29.00,13.18,2.5,1
5,78.22,0,1,29.6,23.10,18.0,1.0,166.26,144.62,124.50,...,4.10,3.40,150.25,141.22,136.5,NaN,46.86,8.68,0.3,1

In [9]:
print(f"The data has {data.shape[0]:,} rows and {data.shape[1]} columns.")

The data has 3,550 rows and 35 columns.

## 3.1 Data Cleaning

In [11]:
df = data.copy()

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3550 entries, 0 to 4430
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          3550 non-null   float64
 1   gender_F     3550 non-null   int64
 2   gender_M     3550 non-null   int64
 3   bic_max      3550 non-null   float64
 4   bic_mean     3550 non-null   float64
 5   bic_min      3550 non-null   float64
 6   bilirubin    2893 non-null   float64
 7   bp_max       3550 non-null   float64
 8   bp_mean      3550 non-null   float64
 9   bp_min       3550 non-null   float64
 10  bun_max      3550 non-null   float64
 11  bun_mean     3550 non-null   float64
 12  bun_min      3550 non-null   float64
 13  Days_in_uci  3550 non-null   float64
 14  fio2         3152 non-null   float64
 15  gcs_max      3550 non-null   float64
 16  gcs_mean     3550 non-null   float64
 17  gcs_min      3550 non-null   float64
 18  hr_max       3550 non-null   float64
 19  hr_mean      3550 non-null   float64
 20  hr_min       3550 non-null   float64
 21  max pao2     3417 non-null   float64
 22  mean pao2    3417 non-null   float64
 23  min pao2     3417 non-null   float64
 24  pot_max      3550 non-null   float64
 25  pot_mean     3550 non-null   float64
 26  pot_min      3550 non-null   float64
 27  sod_max      3550 non-null   float64
 28  sod_mean     3550 non-null   float64
 29  sod_min      3550 non-null   float64
 30  temp         2325 non-null   float64
 31  wbc_max      3550 non-null   float64
 32  wbc_mean     3550 non-null   float64
 33  wbc_min      3550 non-null   float64
 34  IHM          3550 non-null   int64
dtypes: float64(32), int64(3)
memory usage: 998.4 KB

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,3550.0,64.286620,15.986639,16.90,54.1125,66.920,77.2075,89.00
gender_F,3550.0,0.424507,0.494338,0.00,0.0000,0.000,1.0000,1.00
gender_M,3550.0,0.575493,0.494338,0.00,0.0000,1.000,1.0000,1.00
bic_max,3550.0,30.055363,5.032318,14.50,27.0000,30.000,33.0000,50.00
bic_mean,3550.0,25.606231,4.147980,12.33,23.1250,25.460,27.8500,44.69
bic_min,3550.0,20.895972,4.388776,5.00,18.0000,21.000,23.5000,39.00
bilirubin,2893.0,1.586049,3.168970,0.00,0.4000,0.700,1.3000,29.50
bp_max,3550.0,140.153299,18.630140,90.79,126.5100,140.155,153.0800,241.00
bp_mean,3550.0,122.734980,14.647909,84.62,111.8750,121.635,132.7400,182.93
bp_min,3550.0,106.023138,13.324255,44.26,97.0400,104.015,113.7075,163.23
bun_max,3550.0,49.267746,34.316147,2.00,24.0000,38.000,65.0000,242.00
bun_mean,3550.0,33.349608,22.733572,1.44,16.8100,26.570,43.1400,180.01
bun_min,3550.0,20.373023,15.873940,1.00,10.0000,15.500,25.0000,145.00
Days_in_uci,3550.0,12.990704,9.637976,5.00,7.0000,10.000,15.0000,98.00
fio2,3152.0,66.174702,21.586581,0.40,50.0000,61.430,83.3300,100.00
gcs_max,3550.0,13.392777,2.443850,3.00,12.2275,14.810,15.0000,15.00
gcs_mean,3550.0,10.514515,2.799937,3.00,8.7800,10.500,12.5800,15.00
gcs_min,3550.0,7.214685,3.549748,3.00,4.0000,7.000,9.3225,15.00
hr_max,3550.0,102.798079,15.494365,52.59,91.9050,102.675,113.1100,174.78
hr_mean,3550.0,87.252792,12.163403,49.74,78.8000,86.815,95.2375,141.74
hr_min,3550.0,73.532600,12.302967,36.38,64.7625,73.000,81.5200,120.32
max pao2,3417.0,225.681299,140.583061,25.00,104.0000,187.000,338.0000,797.00
mean pao2,3417.0,158.373377,88.775638,25.00,90.0000,133.670,211.0000,565.00
min pao2,3417.0,105.881182,76.927590,16.00,61.0000,84.000,121.0000,565.00
pot_max,3550.0,4.766490,0.602500,3.60,4.3500,4.670,5.1000,9.40
pot_mean,3550.0,4.047318,0.302202,3.23,3.8400,4.020,4.2200,5.92
pot_min,3550.0,3.490163,0.321318,2.17,3.3000,3.500,3.7000,5.20
sod_max,3550.0,144.345806,4.770282,127.00,141.0000,144.000,147.5000,172.43
sod_mean,3550.0,139.628034,3.691264,118.98,137.3925,139.750,142.0100,154.90
sod_min,3550.0,134.872775,4.356401,100.00,132.3300,135.000,138.0000,149.33
temp,2325.0,36.892133,1.006496,31.67,36.2900,36.890,37.5200,41.30
wbc_max,3550.0,18.824369,12.861885,0.10,13.0000,16.615,22.1000,521.45
wbc_mean,3550.0,12.569597,9.247942,0.10,9.2400,11.620,14.5575,448.40
wbc_min,3550.0,8.219685,7.039966,0.05,5.8000,7.600,9.9000,351.10
IHM,3550.0,0.274366,0.446257,0.00,0.0000,0.000,1.0000,1.00

In [19]:
# checking duplicates 

print(f"The data has {df.duplicated().sum()} duplicate rows.")

The data has 0 duplicate rows.

In [35]:
# checking for missing values

missing = pd.DataFrame({
    "missing_count":df.isna().sum(), 
    "missing_percentage":df.isna().sum()/df.shape[0] *100
    })
missing[missing['missing_count'] > 0].sort_values(by='missing_count', ascending=False)

           missing_count  missing_percentage
temp                1225           34.507042
bilirubin            657           18.507042
fio2                 398           11.211268
max pao2             133            3.746479
mean pao2            133            3.746479
min pao2             133            3.746479

# 4. Modelling

# 5. Deployment